server:
    port: 8080
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: client
                  uri: lb://CLIENT
                  predicates:
                      - Path=/api/v1/clients/**
                  filters:
                      - RewritePath=/api/v1/clients/?(?<segment>.*), /${segment}
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true